### PR TITLE
Add support for Convex16 and Convex32

### PR DESCRIPTION
**Pull request by lmontaut**
So far, the indices of neighbors and polygons of a `Convex` were stored on `uint32`.
This PR introduces `Convex16` and `Convex32` to store these indices either on `uint16` or `uint32`.
Along with the float PR #665, this allows to divide by two the memory footprint of a `Convex` (double/uint32 vs float/uint16).

### CODE REVIEW

**Review by jcarpent — DISMISSED** [review]

**Comment by rhaschke** [comment]
Since this PR was merged, coal [doesn't build on Ubuntu 22.04 anymore](https://productionresultssa3.blob.core.windows.net/actions-results/98cfe68c-905a-4008-bfee-bb43783eb42a/workflow-job-run-4a4ae026-12f8-5097-aa22-bded75a4a500/logs/job/job-logs.txt?rsct=text%2Fplain&se=2025-04-21T18%3A47%3A59Z&sig=0hsQwrE7yUBUwNZG0sWq0%2FfEk8Ng1RwtP9hiTt2dSJg%3D&ske=2025-04-22T05%3A09%3A59Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2025-04-21T17%3A09%3A59Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2025-01-05&sp=r&spr=https&sr=b&st=2025-04-21T18%3A37%3A54Z&sv=2025-01-05). Here is a subset of errors:
```
2025-04-20T20:28:50.9776049Z In file included from /<<BUILDDIR>>package/python/collision-geometries.cc:70:
2025-04-20T20:28:50.9776566Z /<<BUILDDIR>>package/.obj-aarch64-linux-gnu/python/doxygen_autodoc/coal/shape/geometric_shapes.h:1669:190: error: expected ‘)’ before ‘const’
2025-04-20T20:28:50.9777114Z  1669 | inline const char* member_func_doc ( coal::ConvexBaseTpl < OtherIndexType >:: coal::ConvexBaseTpl::SupportWarmStartPolytope (coal::ConvexBaseTpl::SupportWarmStartPolytope::*function_ptr) () const)
2025-04-20T20:28:50.9777243Z       |                                    ~                                                                                                                                                         ^~~~~~
2025-04-20T20:28:50.9777360Z       |                                                                                                                                                                                              )
2025-04-20T20:28:50.9778210Z /<<BUILDDIR>>package/.obj-aarch64-linux-gnu/python/doxygen_autodoc/coal/shape/geometric_shapes.h:1677:124: error: ‘template<class OtherIndexType> boost::python::detail::keywords<1> doxygen::member_func_args’ redeclared as different kind of entity
2025-04-20T20:28:50.9778827Z  1677 | inline boost::python::detail::keywords<1> member_func_args ( coal::ConvexBaseTpl < OtherIndexType >:: coal::ConvexBaseTpl::SupportWarmStartPolytope (coal::ConvexBaseTpl::SupportWarmStartPolytope::*function_ptr) () const)
2025-04-20T20:28:50.9778942Z       |                                                                                                                            ^~~~~~~~~~~~~~~~~~~~~~~~
2025-04-20T20:28:50.9780082Z /<<BUILDDIR>>package/.obj-aarch64-linux-gnu/python/doxygen_autodoc/coal/shape/geometric_shapes.h:1657:43: note: previous declaration ‘boost::python::detail::keywords<2> doxygen::member_func_args(std::pair<coal::Sphere, coal::Transform3s> (coal::Sphere::*)(coal::Scalar) const)’
2025-04-20T20:28:50.9780489Z  1657 | inline boost::python::detail::keywords<2> member_func_args (std::pair< coal::Sphere , coal::Transform3s > (coal::Sphere::*function_ptr) (const coal::Scalar) const)
2025-04-20T20:28:50.9780723Z       |                                           ^~~~~~~~~~~~~~~~
2025-04-20T20:28:50.9781493Z /<<BUILDDIR>>package/.obj-aarch64-linux-gnu/python/doxygen_autodoc/coal/shape/geometric_shapes.h:1677:156: error: ‘template<class _IndexType> class coal::ConvexBaseTpl’ used without template arguments
2025-04-20T20:28:50.9782115Z  1677 | inline boost::python::detail::keywords<1> member_func_args ( coal::ConvexBaseTpl < OtherIndexType >:: coal::ConvexBaseTpl::SupportWarmStartPolytope (coal::ConvexBaseTpl::SupportWarmStartPolytope::*function_ptr) () const)
2025-04-20T20:28:50.9782227Z       |                                                                                                                                                            ^~~~~~~~~~~~~
2025-04-20T20:28:50.9782728Z /<<BUILDDIR>>package/.obj-aarch64-linux-gnu/python/doxygen_autodoc/coal/shape/geometric_shapes.h:1677:197: error: expected unqualified-id before ‘*’ token
2025-04-20T20:28:50.9783352Z  1677 | inline boost::python::detail::keywords<1> member_func_args ( coal::ConvexBaseTpl < OtherIndexType >:: coal::ConvexBaseTpl::SupportWarmStartPolytope (coal::ConvexBaseTpl::SupportWarmStartPolytope::*function_ptr) () const)
2025-04-20T20:28:50.9783643Z       |                                                                                                                                                                                                     ^
2025-04-20T20:28:50.9784411Z /<<BUILDDIR>>package/.obj-aarch64-linux-gnu/python/doxygen_autodoc/coal/shape/geometric_shapes.h:1677:198: error: ‘function_ptr’ was not declared in this scope; did you mean ‘boost::python::detail::function_ptr’?
2025-04-20T20:28:50.9785029Z  1677 | inline boost::python::detail::keywords<1> member_func_args ( coal::ConvexBaseTpl < OtherIndexType >:: coal::ConvexBaseTpl::SupportWarmStartPolytope (coal::ConvexBaseTpl::SupportWarmStartPolytope::*function_ptr) () const)
2025-04-20T20:28:50.9785158Z       |                                                                                                                                                                                                      ^~~~~~~~~~~~
2025-04-20T20:28:50.9785326Z       |                                                                                                                                                                                                      boost::python::detail::function_ptr
```

**Comment by jorisv** [comment]
Hello @rhaschke,

There is a similar issue on Windows. I will investigate.
In the mean time, you can disable autodoc generation with this CMake option: ENABLE_PYTHON_DOXYGEN_AUTODOC

**Comment by jorisv** [comment]
@rhaschke Can you open an issue with all details to reproduce ?

It seem the Windows issue is not the same.
